version: "3.1"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quiz-app-db
    ports:
      - "5432:5432"
